# Generated by Django 3.1 on 2021-06-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzamodel',
            old_name='pizza',
            new_name='price',
        ),
    ]
