# Generated by Django 3.1 on 2021-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0003_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('ordereditems', models.CharField(max_length=10)),
            ],
        ),
    ]
